import { FormConfig } from '@/types/form';
import { defaultThemes } from './themes';
import { generateId } from './utils';

export const sampleContactForm: FormConfig = {
  id: generateId(),
  title: 'Contact Us',
  description: 'Get in touch with our team. We\'d love to hear from you!',
  theme: defaultThemes[0], // Modern Blue
  fields: [
    {
      id: generateId(),
      type: 'text',
      label: 'Full Name',
      placeholder: 'Enter your full name',
      required: true,
      validation: [
        {
          type: 'minLength',
          value: 2,
          message: 'Name must be at least 2 characters long',
        },
      ],
      properties: {
        width: 'full',
        size: 'medium',
        style: {
          backgroundColor: '',
          textColor: '',
          borderColor: '',
          borderRadius: '',
          fontSize: '',
          fontWeight: '',
          padding: '',
        },
      },
    },
    {
      id: generateId(),
      type: 'email',
      label: 'Email Address',
      placeholder: 'your.email@example.com',
      required: true,
      validation: [],
      properties: {
        width: 'half',
        size: 'medium',
        style: {
          backgroundColor: '',
          textColor: '',
          borderColor: '',
          borderRadius: '',
          fontSize: '',
          fontWeight: '',
          padding: '',
        },
      },
    },
    {
      id: generateId(),
      type: 'phone',
      label: 'Phone Number',
      placeholder: '+1 (555) 123-4567',
      required: false,
      validation: [],
      properties: {
        width: 'half',
        size: 'medium',
        style: {
          backgroundColor: '',
          textColor: '',
          borderColor: '',
          borderRadius: '',
          fontSize: '',
          fontWeight: '',
          padding: '',
        },
      },
    },
    {
      id: generateId(),
      type: 'select',
      label: 'How did you hear about us?',
      placeholder: 'Select an option',
      required: true,
      options: [
        'Search Engine',
        'Social Media',
        'Friend Referral',
        'Advertisement',
        'Other',
      ],
      validation: [],
      properties: {
        width: 'full',
        size: 'medium',
        style: {
          backgroundColor: '',
          textColor: '',
          borderColor: '',
          borderRadius: '',
          fontSize: '',
          fontWeight: '',
          padding: '',
        },
      },
    },
    {
      id: generateId(),
      type: 'textarea',
      label: 'Message',
      placeholder: 'Tell us about your project or inquiry...',
      required: true,
      validation: [
        {
          type: 'minLength',
          value: 10,
          message: 'Message must be at least 10 characters long',
        },
      ],
      properties: {
        width: 'full',
        size: 'medium',
        style: {
          backgroundColor: '',
          textColor: '',
          borderColor: '',
          borderRadius: '',
          fontSize: '',
          fontWeight: '',
          padding: '',
        },
      },
    },
  ],
  settings: {
    submitButtonText: 'Send Message',
    successMessage: 'Thank you for contacting us! We\'ll get back to you soon.',
    allowMultipleSubmissions: false,
    showProgressBar: true,
    enableAutoSave: true,
  },
};

export const sampleSurveyForm: FormConfig = {
  id: generateId(),
  title: 'Customer Satisfaction Survey',
  description: 'Help us improve our services by sharing your feedback.',
  theme: defaultThemes[1], // Elegant Purple
  fields: [
    {
      id: generateId(),
      type: 'radio',
      label: 'How would you rate our service?',
      required: true,
      options: [
        'Excellent',
        'Good',
        'Average',
        'Poor',
        'Very Poor',
      ],
      validation: [],
      properties: {
        width: 'full',
        size: 'medium',
        style: {
          backgroundColor: '',
          textColor: '',
          borderColor: '',
          borderRadius: '',
          fontSize: '',
          fontWeight: '',
          padding: '',
        },
      },
    },
    {
      id: generateId(),
      type: 'checkbox',
      label: 'Which features do you use most? (Select all that apply)',
      required: false,
      options: [
        'Customer Support',
        'Online Portal',
        'Mobile App',
        'Email Notifications',
        'Reporting Dashboard',
      ],
      validation: [],
      properties: {
        width: 'full',
        size: 'medium',
        style: {
          backgroundColor: '',
          textColor: '',
          borderColor: '',
          borderRadius: '',
          fontSize: '',
          fontWeight: '',
          padding: '',
        },
      },
    },
    {
      id: generateId(),
      type: 'number',
      label: 'On a scale of 1-10, how likely are you to recommend us?',
      placeholder: 'Enter a number between 1-10',
      required: true,
      validation: [
        {
          type: 'min',
          value: 1,
          message: 'Rating must be at least 1',
        },
        {
          type: 'max',
          value: 10,
          message: 'Rating cannot exceed 10',
        },
      ],
      properties: {
        width: 'half',
        size: 'medium',
        style: {
          backgroundColor: '',
          textColor: '',
          borderColor: '',
          borderRadius: '',
          fontSize: '',
          fontWeight: '',
          padding: '',
        },
      },
    },
    {
      id: generateId(),
      type: 'textarea',
      label: 'Additional Comments',
      placeholder: 'Share any additional feedback or suggestions...',
      required: false,
      validation: [],
      properties: {
        width: 'full',
        size: 'medium',
        style: {
          backgroundColor: '',
          textColor: '',
          borderColor: '',
          borderRadius: '',
          fontSize: '',
          fontWeight: '',
          padding: '',
        },
      },
    },
  ],
  settings: {
    submitButtonText: 'Submit Survey',
    successMessage: 'Thank you for your valuable feedback!',
    allowMultipleSubmissions: false,
    showProgressBar: true,
    enableAutoSave: true,
  },
};

export const sampleRegistrationForm: FormConfig = {
  id: generateId(),
  title: 'Event Registration',
  description: 'Register for our upcoming conference and secure your spot.',
  theme: defaultThemes[2], // Minimal Gray
  fields: [
    {
      id: generateId(),
      type: 'text',
      label: 'First Name',
      placeholder: 'Enter your first name',
      required: true,
      validation: [],
      properties: {
        width: 'half',
        size: 'medium',
        style: {
          backgroundColor: '',
          textColor: '',
          borderColor: '',
          borderRadius: '',
          fontSize: '',
          fontWeight: '',
          padding: '',
        },
      },
    },
    {
      id: generateId(),
      type: 'text',
      label: 'Last Name',
      placeholder: 'Enter your last name',
      required: true,
      validation: [],
      properties: {
        width: 'half',
        size: 'medium',
        style: {
          backgroundColor: '',
          textColor: '',
          borderColor: '',
          borderRadius: '',
          fontSize: '',
          fontWeight: '',
          padding: '',
        },
      },
    },
    {
      id: generateId(),
      type: 'email',
      label: 'Email Address',
      placeholder: 'your.email@company.com',
      required: true,
      validation: [],
      properties: {
        width: 'full',
        size: 'medium',
        style: {
          backgroundColor: '',
          textColor: '',
          borderColor: '',
          borderRadius: '',
          fontSize: '',
          fontWeight: '',
          padding: '',
        },
      },
    },
    {
      id: generateId(),
      type: 'select',
      label: 'Company Size',
      placeholder: 'Select your company size',
      required: true,
      options: [
        '1-10 employees',
        '11-50 employees',
        '51-200 employees',
        '201-1000 employees',
        '1000+ employees',
      ],
      validation: [],
      properties: {
        width: 'half',
        size: 'medium',
        style: {
          backgroundColor: '',
          textColor: '',
          borderColor: '',
          borderRadius: '',
          fontSize: '',
          fontWeight: '',
          padding: '',
        },
      },
    },
    {
      id: generateId(),
      type: 'select',
      label: 'Industry',
      placeholder: 'Select your industry',
      required: true,
      options: [
        'Technology',
        'Healthcare',
        'Finance',
        'Education',
        'Manufacturing',
        'Retail',
        'Other',
      ],
      validation: [],
      properties: {
        width: 'half',
        size: 'medium',
        style: {
          backgroundColor: '',
          textColor: '',
          borderColor: '',
          borderRadius: '',
          fontSize: '',
          fontWeight: '',
          padding: '',
        },
      },
    },
    {
      id: generateId(),
      type: 'checkbox',
      label: 'Session Preferences',
      required: false,
      options: [
        'Keynote Sessions',
        'Technical Workshops',
        'Networking Events',
        'Panel Discussions',
      ],
      validation: [],
      properties: {
        width: 'full',
        size: 'medium',
        style: {
          backgroundColor: '',
          textColor: '',
          borderColor: '',
          borderRadius: '',
          fontSize: '',
          fontWeight: '',
          padding: '',
        },
      },
    },
  ],
  settings: {
    submitButtonText: 'Register Now',
    successMessage: 'Registration successful! Check your email for confirmation.',
    allowMultipleSubmissions: false,
    showProgressBar: true,
    enableAutoSave: true,
  },
};

export const sampleForms = [
  sampleContactForm,
  sampleSurveyForm,
  sampleRegistrationForm,
];
